version: "3.8"
services:
  mysqldb:
    image: mysql
    env_file: 
      - .env
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - country-mysql

  countries-be:
    image: countries-be
    build: .
    env_file: 
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/countries_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Turkey&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb
    networks:
      - country-mysql

networks:
  country-mysql:
